#!/bin/bash
#192. Word Frequency
#Write a bash script to calculate the frequency of each word in a text file words.txt.
#
#For simplicity sake, you may assume:
#	words.txt contains only lowercase characters and space ' ' characters.
#	Each word must consist of lowercase characters only.
#	Words are separated by one or more whitespace characters.


declare -A countWords

while read line
do
	for i in $line
	do
		(( countWords[$i]++ ))
	done
done < words.txt


for word in "${!countWords[@]}"
do
	echo "$word ${countWords[$word]}"
done | sort -k2,2nr -k1,1




