#!/bin/bash
#Valid Phone Numbers
#Given a text file file.txt that contains a list of phone numbers (one per line),
#write a one-liner bash script to print all valid phone numbers.
#You may assume that a valid phone number must appear in one of the following two formats:
#(xxx) xxx-xxxx or xxx-xxx-xxxx. (x means a digit)
#You may also assume each line in the text file must not contain leading or trailing white spaces.

regex='^(\([0-9]{3}\) [0-9]{3}-[0-9]{4}|^[0-9]{3}-[0-9]{3}-[0-9]{4})$'

while read line
do
	if [[ $line =~ $regex ]]
	then
		echo "$line"
	fi
done < file.txt

