#!/bin/bash

lst=(1 2 3 4 5 6 7 8 9 0)

echo "Введите число, на которое будет выполнено смещение массива"

echo "${lst[@]}"

read

len=${#lst[@]}

if [[ -z "$REPLY"  || "$REPLY" -eq '0' || "$REPLY" -eq $len ]] 
then
	echo "${lst[@]}"
	exit 0
fi

k=$(( $REPLY % $len ))

st=$(( $len - $k ))

echo "${lst[@]:$st:$len} ${lst[@]:0:$st}"

