#!/bin/bash

SECONDS=0
count=0
start_time=$(date "+%s")

tail -n0 -F -- "access.log1" 2>/dev/null | while read -r line
do 
	(( count++ ))
	
	now_time=$(date "+%s")
	diff=$(( $now_time - $start_time ))
	if (( $diff >= 60 ))
		then
		if (( count > 1000 ))
			then
			echo "возможно атака" >> attack.log
		fi
		count=0
		start_time=$now_time
	fi

done

#Проверка
# for i in {1..1200}; do echo "test $i" >> access.log1; done






