#!/bin/bash

check=$(sudo ss -tuln | awk 'NR>1 {print$5}' | sort | cut -d : -f 2 | uniq)

while read line
do
	if ! echo "$check" | grep -q -w "$line"
	then
		echo "$(date '+%F %T') порт $line не прослушивается" >> ports_check.log
	fi

done < ports
