#!/bin/bash

if [ -z "$1" ]
	then
		echo "Использование: $0 <путь до файла>"
		exit 1
fi

if [ -f "$1" ]
	then
	echo "Это файл"
elif [ -d "$1" ]
	then 
	echo "Это директория" 
else
	echo "Нет такого файла или директории"
fi

