#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] 
	then
	echo "Использование: $0 <число1> <оператор> <чиcло2>"
	exit 1
fi

if [ "$2" == "+" ]
	then
	echo "$(( $1 + $3 ))"
elif [ "$2" == "-" ]
	then
	echo "$(( $1 - $3 ))"
elif [ "$2" == "*" ]
	then
	echo "$(( $1 * $3 ))"
else
	echo "$(( $1 / $3 ))"
fi

